[project]
name = "pdftool"
version = "1.0.0"
description = "CLI tool untuk convert dan compress file PDF, JPG, DOC/DOCX"
requires-python = ">=3.10"
dependencies = [
    "pypdf",
    "pdf2image",
    "Pillow",
    "pikepdf",
    "python-docx",
    "pdf2docx",
]

[project.scripts]
pdftool = "pdftool.cli:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
